name: DatasetProcessingWorkflow
on: [workflow_dispatch]
  # workflow_run:
  #   workflows: ["dataset_loading.yml"]
  #   types:
  #     - completed
jobs:

  PreprocessData:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: install script requirements
        run: pip install -r src/requirements.txt
      - name: preprocess_data
        run: python src/dataset_processing.py
      - name: commit changes
        uses: EndBug/add-and-commit@v9.1.1
        with:
          default_author: github_actions