name: DatasetLoadingWorkflow
on: [workflow_dispatch]
jobs:
  LoadDataset:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: install MLHub API
        run: pip install radiant_mlhub
      - name: install dataset
        env:
          API_KEY: ${{secrets.API_KEY}}
        run: python src/dataset_loading.py
      - name: unpack dataset archive
        run: tar -xvzf ref_agrifieldnet_competition_v1.tar.gz
      - name: delete archive
        run: rm ref_agrifieldnet_competition_v1.tar.gz
      - name: install script requirements
        run: pip install -r requirements.txt
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ref_agrifieldnet_competition_v1
          path: ref_agrifieldnet_competition_v1