name: MainWorkflow
# on:
#   workflow_run:
#     workflows: ["dataset_loading.yml"]
#     types:
#       - completed
on: [workflow_dispatch]
jobs:


  PreprocessData:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: install script requirements
        run: pip install -r requirements.txt
      - name: preprocess_data
        run: python src/dataset_processing.py
      - name: commit changes
        uses: EndBug/add-and-commit@v9.1.1
        with:
          default_author: github_actions


  TrainRandomForest:
    runs-on: ubuntu-latest
    needs: [PreprocessData]
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: Pull changes
        run: |
          git pull origin HEAD:${{ github.ref }}
      - name: install script requirements
        run: pip install -r requirements.txt
      - name: training RFC
        run: python src/training.py "RFC"
      - name: commit changes
        uses: EndBug/add-and-commit@v9.1.1
        with:
          default_author: github_actions


  FineTuningRandomForest:
    runs-on: ubuntu-latest
    needs: [TrainRandomForest]
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: Pull changes
        run: |
          git pull origin HEAD:${{ github.ref }}
      - name: install script requirements
        run: pip install -r requirements.txt
      - name: fine tuning RFC
        run: python src/training.py "RFC"
      - name: commit changes
        uses: EndBug/add-and-commit@v9.1.1
        with:
          default_author: github_actions


  EvalRandomForest:
    runs-on: ubuntu-latest
    needs: [FineTuningRandomForest]
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: Pull changes
        run: |
          git pull origin HEAD:${{ github.ref }}
      - name: install script requirements
        run: pip install -r requirements.txt
      - name: RFC evaluation
        run: python src/evaluation.py "RFC"     
      - name: commit changes
        uses: EndBug/add-and-commit@v9.1.1
        with:
          default_author: github_actions


  TrainKNN:
    runs-on: ubuntu-latest
    needs: EvalRandomForest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: Pull changes
        run: |
          git pull origin HEAD:${{ github.ref }}
      - name: install script requirements
        run: pip install -r requirements.txt
      - name: training knn
        run: python src/training.py "KNN"
      - name: commit changes
        uses: EndBug/add-and-commit@v9.1.1
        with:
          default_author: github_actions


  FineTuningKNN:
    runs-on: ubuntu-latest
    needs: [TrainKNN]
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: Pull changes
        run: |
          git pull origin HEAD:${{ github.ref }}
      - name: install script requirements
        run: pip install -r requirements.txt
      - name: fine tuning knn
        run: python src/training.py "KNN"
      - name: commit changes
        uses: EndBug/add-and-commit@v9.1.1
        with:
          default_author: github_actions


  EvalKNN:
    runs-on: ubuntu-latest
    needs: [FineTuningKNN]
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: Pull changes
        run: |
          git pull origin HEAD:${{ github.ref }}
      - name: install script requirements
        run: pip install -r requirements.txt
      - name: KNN evaluation
        run: python src/evaluation.py "KNN"
      - name: commit changes
        uses: EndBug/add-and-commit@v9.1.1
        with:
          default_author: github_actions
  

  SelectModel:
    runs-on: ubuntu-latest
    needs: [EvalKNN]
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: Pull changes
        run: |
          git pull origin HEAD:${{ github.ref }}
      - name: install script requirements
        run: pip install -r requirements.txt
      - name: select best model
        run: python src/model_selection.py
      - name: commit changes
        uses: EndBug/add-and-commit@v9.1.1
        with:
          default_author: github_actions    

        
  Deploy:
    runs-on: self-hosted
    needs: [SelectModel]
    steps:
#       - name: checkout repo content
#         uses: actions/checkout@v3
      - name: Pull changes
        run: |
          git pull origin HEAD:${{ github.ref }}
      - name: deploy 
        run: docker run -p 5000:5000 crop-types
