name: MainWorkflow
on: [workflow_dispatch]
jobs:


  LoadDataset:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: install MLHub API
        run: pip install radiant_mlhub
      - name: install dataset
        env:
          API_KEY: ${{secrets.API_KEY}}
        run: python src/dataset_loading.py
      - name: unpack dataset archive
        run: tar -xvzf ref_agrifieldnet_competition_v1.tar.gz
      - name: delete archive
        run: rm ref_agrifieldnet_competition_v1.tar.gz
      - name: install script requirements
        run: pip install -r requirements.txt
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: reports/


  PreprocessData:
    runs-on: ubuntu-latest
    needs: [LoadDataset]
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: reports/
      - name: install script requirements
        run: pip install -r requirements.txt
      - name: preprocess_data
        run: python src/dataset_processing.py
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: reports/


  TrainRandomForest:
    runs-on: ubuntu-latest
    needs: [PreprocessData]
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: reports/
      - name: install script requirements
        run: pip install -r requirements.txt
      - name: train_random_forest_classifier
        run: python src/training.py "RFC"
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: reports/


  FineTuningRandomForest:
    runs-on: ubuntu-latest
    needs: [TrainRandomForest]
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: reports/
      - name: install script requirements
        run: pip install -r requirements.txt
      - name: fine_tuning_random_forest_classifier
        run: python src/training.py "RFC"
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: reports/


  EvalRandomForest:
    runs-on: ubuntu-latest
    needs: [FineTuningRandomForest]
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: reports/
      - name: install script requirements
        run: pip install -r requirements.txt
      - name: eval_random_forest_classifier
        run: python src/evaluation.py "RFC"     
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: reports/



  TrainKNN:
    runs-on: ubuntu-latest
    needs: [PreprocessData]
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: reports/
      - name: install script requirements
        run: pip install -r requirements.txt
      - name: train_knn
        run: python src/training.py "KNN"
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: reports/



  FineTuningKNN:
    runs-on: ubuntu-latest
    needs: [TrainKNN]
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: reports/
      - name: install script requirements
        run: pip install -r requirements.txt
      - name: fine_tuning_knn
        run: python src/training.py "KNN"
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: reports/



  EvalKNN:
    runs-on: ubuntu-latest
    needs: [FineTuningKNN]
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: reports/
      - name: install script requirements
        run: pip install -r requirements.txt
      - name: KNN_evaluating
        run: python src/evaluation.py "KNN"
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: reports/
  

  
  SelectModel:
    runs-on: ubuntu-latest
    needs: [EvalRandomForest, EvalKNN]
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: reports/
      - name: install script requirements
        run: pip install -r requirements.txt
      - name: select best model
        run: python src/model_selection.py
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: reports/

        
  Deploy:
    runs-on: self-hosted
    needs: [SelectModel]
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: reports/
      - name: install script requirements
        run: pip install -r requirements.txt
      - name: deploy best model with Flask
        run: docker run -p 5000:5000 crop-types